version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=petadoption
      - POSTGRES_USER=petadoption
      - POSTGRES_PASSWORD=petadoption
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/petadoption
      - SPRING_DATASOURCE_USERNAME=petadoption
      - SPRING_DATASOURCE_PASSWORD=petadoption
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: sh -c "./mvnw spring-boot:run -Dspring-boot.run.jvmArguments='-Dspring.devtools.livereload.enabled=true'"

volumes:
  db-data:
