spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petadoption?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: petadoption
    password: petadoption
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            show_sql: true
            use_sql_comments: true

